# Generated by Django 5.0.2 on 2024-06-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
