# Generated by Django 5.0.2 on 2024-06-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0002_userreg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
    ]
