# Generated by Django 5.0.2 on 2024-06-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0004_remove_userreg_image_userreg_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreg',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='userreg',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
