# Generated by Django 5.0.2 on 2024-06-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0006_alter_userreg_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='master_profile_images/')),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
