# Generated by Django 5.0.2 on 2024-06-27 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0007_masteruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterUser',
        ),
    ]
