# Generated by Django 5.0.2 on 2024-06-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0009_master'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='photo',
            new_name='img',
        ),
    ]
