# Generated by Django 5.0.2 on 2024-06-27 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0010_rename_photo_master_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='master',
            name='description',
        ),
        migrations.RemoveField(
            model_name='master',
            name='type',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='state',
        ),
        migrations.AddField(
            model_name='master',
            name='field',
            field=models.CharField(default='Default Value', max_length=50),
        ),
        migrations.AddField(
            model_name='master',
            name='lat',
            field=models.CharField(default='Default Lat', max_length=50),
        ),
        migrations.AddField(
            model_name='master',
            name='lon',
            field=models.CharField(default='Default Lon', max_length=50),
        ),
        migrations.AddField(
            model_name='master',
            name='phone',
            field=models.CharField(default='Not Provided', max_length=50),
        ),
        migrations.AddField(
            model_name='master',
            name='qual',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreg',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreg',
            name='name',
            field=models.CharField(default='Not Provided', max_length=50),
        ),
        migrations.AddField(
            model_name='userreg',
            name='phone',
            field=models.CharField(default='Not Provided', max_length=50),
        ),
        migrations.AlterField(
            model_name='master',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='master',
            name='img',
            field=models.ImageField(default=0, upload_to='Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='master',
            name='name',
            field=models.CharField(default='Not Provided', max_length=50),
        ),
        migrations.AlterField(
            model_name='master',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
