# Generated by Django 5.0.2 on 2024-06-27 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0011_remove_master_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='master',
            name='lon',
        ),
    ]
