# Generated by Django 5.0.2 on 2024-06-28 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0014_userreg_email_alter_master_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='email',
        ),
        migrations.RemoveField(
            model_name='master',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='email',
        ),
    ]
