# Generated by Django 5.0.2 on 2024-06-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0015_remove_master_email_remove_master_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='name',
            field=models.CharField(default='Not Provided', max_length=50),
        ),
    ]
