# Generated by Django 5.0.2 on 2024-06-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0016_master_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
