# Generated by Django 5.0.2 on 2024-06-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0017_master_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='name',
        ),
    ]
