# Generated by Django 5.0.2 on 2024-06-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0018_remove_master_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='username',
            field=models.CharField(default='name', max_length=150),
        ),
        migrations.AlterField(
            model_name='master',
            name='address',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='master',
            name='field',
            field=models.CharField(default='Default Value', max_length=100),
        ),
        migrations.AlterField(
            model_name='master',
            name='qual',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
    ]
