# Generated by Django 5.0.2 on 2024-06-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0020_writingsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingsubmission',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
