# Generated by Django 5.0.2 on 2024-06-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0021_writingsubmission_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingsubmission',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('under_review', 'Under Review'), ('completed', 'Completed')], default='opened', max_length=20),
        ),
    ]
