# Generated by Django 5.0.2 on 2024-06-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0023_alter_writingsubmission_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writingsubmission',
            old_name='master_check_mark',
            new_name='spelling_mark',
        ),
    ]
