# Generated by Django 5.0.2 on 2024-06-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0025_remove_writingsubmission_grammatical_mark_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackdetails',
            old_name='grammatical_mark',
            new_name='grammar_mark',
        ),
        migrations.RenameField(
            model_name='feedbackdetails',
            old_name='master_mark',
            new_name='total_mark',
        ),
        migrations.RemoveField(
            model_name='feedbackdetails',
            name='reviewed_by',
        ),
    ]
