# Generated by Django 5.0.2 on 2024-06-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0026_rename_grammatical_mark_feedbackdetails_grammar_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackdetails',
            name='grammar_mark',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='feedbackdetails',
            name='plagiarism_mark',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='feedbackdetails',
            name='spelling_mark',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='feedbackdetails',
            name='total_mark',
            field=models.FloatField(default=0),
        ),
    ]
