# Generated by Django 5.0.2 on 2024-06-29 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0030_alter_feedbackdetails_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackdetails',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pen.writingsubmission'),
        ),
    ]
