# Generated by Django 5.0.2 on 2024-06-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0031_alter_feedbackdetails_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackdetails',
            name='reviewed_by',
            field=models.CharField(default='', max_length=150),
        ),
    ]
